# syntax=docker/dockerfile:1

FROM ruby:3.3

# Node.js, PostgreSQLクライアント, その他必要なもの
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs postgresql-client

WORKDIR /app

# Gemfileだけ先にコピーしてbundle install
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリ全体をコピー
COPY . .

# 環境変数
ENV RAILS_ENV=development

EXPOSE 3000

USER root

CMD ["bin/rails", "server", "-b", "0.0.0.0"]
